import type { ModelProvider } from "../providers/types.js";
import { runSubagent } from "../subagents/runner.js";
import { reviewer } from "../subagents/profiles.js";
import type { QualityGateOptions } from "../config/config.js";
import type { WorkerTask, WorkerQualityGate, QualityFinding } from "./types.js";

export interface RunQualityGateInput {
  workspaceRoot: string;
  provider: ModelProvider;
  parentModel: string;
  subagentModel?: string;
  compactAt: number;
  signal: AbortSignal;
  task: WorkerTask;
  patchText: string;
  changedFiles: string[];
  deterministicSummary: string;
  options: QualityGateOptions;
  reviewerRunner?: typeof runSubagent;
}

const SEVERITY_LEVELS: Record<string, number> = {
  low: 1,
  medium: 2,
  high: 3,
  critical: 4,
};

export interface ParsedReviewerOutput {
  verdict: "pass" | "needs_revision" | "block";
  findings: QualityFinding[];
}

/**
 * Find the last top-level `{...}` block and JSON.parse it; null on failure.
 */
function extractLastJsonObject(text: string): unknown {
  const end = text.lastIndexOf("}");
  if (end === -1) return null;
  let depth = 0;
  let inString = false;
  for (let i = end; i >= 0; i--) {
    const ch = text[i];
    if (inString) {
      if (ch === '"' && !isEscaped(text, i)) inString = false;
      continue;
    }
    if (ch === '"' && !isEscaped(text, i)) {
      inString = true;
    } else if (ch === "}") {
      depth++;
    } else if (ch === "{") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(text.slice(i, end + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function isEscaped(text: string, i: number): boolean {
  let n = 0;
  for (let j = i - 1; j >= 0 && text[j] === "\\"; j--) n++;
  return n % 2 === 1;
}

/**
 * Pure parser and normalizer for reviewer output.
 * Truncates claim, evidence, and path strings, and caps findings count.
 */
export function parseAndNormalizeReviewerOutput(text: string): ParsedReviewerOutput {
  const json = extractLastJsonObject(text);
  if (!json || typeof json !== "object") {
    throw new Error("Malformed reviewer output: not a valid JSON object");
  }
  const raw = json as Record<string, unknown>;

  let verdict: "pass" | "needs_revision" | "block" = "block";
  if (raw.verdict === "pass" || raw.verdict === "needs_revision" || raw.verdict === "block") {
    verdict = raw.verdict;
  } else {
    throw new Error(`Malformed reviewer output: invalid verdict "${raw.verdict}"`);
  }

  const rawFindings = Array.isArray(raw.findings) ? raw.findings : [];
  const findings: QualityFinding[] = [];

  for (const f of rawFindings) {
    if (findings.length >= 20) break; // cap findings count
    if (!f || typeof f !== "object") continue;
    const rf = f as Record<string, unknown>;

    let severity: "critical" | "high" | "medium" | "low" = "medium";
    if (rf.severity === "critical" || rf.severity === "high" || rf.severity === "medium" || rf.severity === "low") {
      severity = rf.severity;
    }

    const claim = typeof rf.claim === "string" ? rf.claim.slice(0, 200) : "Unknown claim";
    const evidence = typeof rf.evidence === "string" ? rf.evidence.slice(0, 200) : undefined;
    const path = typeof rf.path === "string" ? rf.path.slice(0, 100) : undefined;

    findings.push({
      severity,
      claim,
      evidence,
      path,
    });
  }

  return { verdict, findings };
}

function buildReviewerTaskPrompt(
  task: WorkerTask,
  patchText: string,
  changedFiles: string[],
  deterministicSummary: string,
  maxPatchBytes: number,
): string {
  let truncatedPatch = patchText;
  if (patchText.length > maxPatchBytes) {
    truncatedPatch = patchText.slice(0, maxPatchBytes) + "\n\n[PATCH TRUNCATED DUE TO SIZE LIMIT]";
  }

  return `You are a read-only peer reviewer. Your task is to review a proposed patch generated by a worker and determine if it should pass, needs revision, or should be blocked.

Worker Task:
Title: ${task.title}
Prompt: ${task.prompt}
Allowed Paths: ${JSON.stringify(task.allowedPaths)}
Forbidden Paths: ${JSON.stringify(task.forbiddenPaths)}

Deterministic Validation & Completeness Summary:
${deterministicSummary}

Changed Files:
${changedFiles.map(f => `- ${f}`).join("\n")}

Proposed Patch:
\`\`\`diff
${truncatedPatch}
\`\`\`

Please inspect the patch and the changed files (using your read-only tools if you need to read file contents).
Evaluate the patch for:
1. Correctness and logic bugs.
2. Syntax or compilation errors.
3. Missing imports or broken references.
4. Completeness against the worker task prompt and expected deliverables.
5. Adherence to allowed/forbidden paths.

You must output your final review as a single JSON object at the very end of your response. Do not wrap it in markdown code blocks other than standard JSON.
The JSON object must strictly follow this schema:
{
  "summary": "A concise summary of your review and verdict.",
  "verdict": "pass" | "needs_revision" | "block",
  "findings": [
    {
      "severity": "critical" | "high" | "medium" | "low",
      "claim": "A specific, clear description of the issue.",
      "evidence": "The specific file:line or patch hunk where the issue occurs.",
      "path": "The relative path of the file containing the issue."
    }
  ],
  "suggestedNextSteps": [
    "Concrete, bounded suggestions for how to fix the issues."
  ]
}

Remember:
- Be objective and precise.
- Use "critical" or "high" severity only for clear correctness, security, or compilation issues.
- Use "medium" or "low" for minor risks, style issues, or nits.
- If the patch is completely correct and meets all requirements, set verdict to "pass".
- If there are minor issues that need fixing but aren't critical, set verdict to "needs_revision".
- If there are major bugs, forbidden path violations, or severe correctness issues, set verdict to "block".`;
}

export async function runQualityGate(input: RunQualityGateInput): Promise<WorkerQualityGate> {
  const startedAt = new Date().toISOString();
  const runner = input.reviewerRunner ?? runSubagent;

  // Assert the reviewer profile contains only read-only tools
  const allowedTools = ["read_file", "grep", "glob", "list_dir", "repo_map", "find_symbols", "list_recent_context"];
  for (const tool of reviewer.allowedTools) {
    if (!allowedTools.includes(tool)) {
      throw new Error(`Security violation: reviewer profile contains non-read-only tool: ${tool}`);
    }
  }

  const taskPrompt = buildReviewerTaskPrompt(
    input.task,
    input.patchText,
    input.changedFiles,
    input.deterministicSummary,
    input.options.maxPatchBytes,
  );

  let passed = true;
  let blocked = false;
  const errors: string[] = [];
  let findings: QualityFinding[] = [];
  let trace = { toolsCalled: [] as string[], turns: 0 };

  try {
    const { result, trace: subagentTrace, finalText } = await runner(reviewer, taskPrompt, {
      workspaceRoot: input.workspaceRoot,
      provider: input.provider,
      parentModel: input.parentModel,
      subagentModel: input.subagentModel,
      contextBudgetTokens: reviewer.contextBudgetTokens,
      compactAt: input.compactAt,
      signal: input.signal,
    });

    trace = {
      toolsCalled: subagentTrace.toolsCalled,
      turns: subagentTrace.turns,
    };

    if (result.errors && result.errors.length > 0) {
      errors.push(...result.errors);
    }

    if (finalText) {
      try {
        const parsed = parseAndNormalizeReviewerOutput(finalText);
        findings = parsed.findings;

        if (parsed.verdict === "block") {
          blocked = true;
          passed = false;
        }

        const minLevel = SEVERITY_LEVELS[input.options.minimumBlockingSeverity] ?? SEVERITY_LEVELS.high;
        for (const f of findings) {
          const fLevel = SEVERITY_LEVELS[f.severity] ?? SEVERITY_LEVELS.medium;
          if (fLevel >= minLevel) {
            blocked = true;
            passed = false;
          }
        }
      } catch (err) {
        errors.push((err as Error).message ?? String(err));
      }
    } else {
      errors.push("No output received from reviewer subagent");
    }
  } catch (err) {
    errors.push((err as Error).message ?? String(err));
  }

  if (errors.length > 0) {
    if (input.options.blockOnReviewerError) {
      blocked = true;
      passed = false;
    }
  }

  return {
    enabled: true,
    passed,
    blocked,
    reviewerProfile: "reviewer",
    model: input.subagentModel ?? input.parentModel,
    startedAt,
    finishedAt: new Date().toISOString(),
    findings,
    errors,
    trace,
  };
}
