/**
 * Pure detection helpers + buildStarterMd for the /init slash command.
 *
 * All functions are deterministic and side-effect-free. I/O (file reads, writes)
 * lives in the slash handler, not here.
 */

// ── Priority ordering for deterministic detection ──────────────────────────
// Each list is ordered by priority (first match wins).

const TEST_FRAMEWORKS = ["vitest", "jest", "mocha", "node:test", "ava", "tape"] as const;
const LINTERS = ["eslint", "oxlint", "biome", "prettier", "ruff"] as const;
const LOCKFILE_MAP: Record<string, string> = {
  "package-lock.json": "npm",
  "pnpm-lock.yaml": "pnpm",
  "yarn.lock": "yarn",
  "bun.lockb": "bun",
};

export interface ProjectProfile {
  hasPackageJson: boolean;
  scripts: Record<string, string>;
  hasTsconfig: boolean;
  tsStrict: boolean | null;
  hasReadme: boolean;
  hasGitignore: boolean;
  hasDockerfile: boolean;
  testFramework: string | null;
  linter: string | null;
  formatter: string | null;
  pkgManager: string | null;
  lang: "ts" | "js" | "python" | "go" | "rust" | "other";
  srcDirs: string[];
  topFiles: string[];
  fileCount: number;
}

/**
 * Detect the test framework from devDependencies.
 * Priority: vitest > jest > mocha > node:test > ava > tape.
 */
export function detectTestFramework(deps: Record<string, string>): string | null {
  for (const fw of TEST_FRAMEWORKS) {
    if (fw in deps) return fw;
  }
  return null;
}

/**
 * Detect the package manager from well-known lockfile basenames.
 * Priority: npm > pnpm > yarn > bun (lockfile-specific).
 */
export function detectPkgManager(lockFiles: string[]): string | null {
  for (const [lock, mgr] of Object.entries(LOCKFILE_MAP)) {
    if (lockFiles.includes(lock)) return mgr;
  }
  return null;
}

/**
 * Detect the linter from devDependencies or well-known config files.
 * Priority: eslint > oxlint > biome > prettier > ruff.
 */
export function detectLinter(
  deps: Record<string, string>,
  _configFiles: string[],
): string | null {
  for (const linter of LINTERS) {
    if (linter in deps) return linter;
  }
  return null;
}

/**
 * Detect the primary language from the extension of source files.
 * Priority order: ts > js > python > go > rust > other.
 */
export function detectLanguage(srcFiles: string[]): "ts" | "js" | "python" | "go" | "rust" | "other" {
  const hasTs = srcFiles.some((f) => f.endsWith(".ts") || f.endsWith(".tsx"));
  if (hasTs) return "ts";
  const hasJs = srcFiles.some((f) => f.endsWith(".js") || f.endsWith(".jsx") || f.endsWith(".mjs") || f.endsWith(".cjs"));
  if (hasJs) return "js";
  const hasPy = srcFiles.some((f) => f.endsWith(".py"));
  if (hasPy) return "python";
  const hasGo = srcFiles.some((f) => f.endsWith(".go"));
  if (hasGo) return "go";
  const hasRs = srcFiles.some((f) => f.endsWith(".rs"));
  if (hasRs) return "rust";
  return "other";
}

// ── Template ───────────────────────────────────────────────────────────────

/**
 * Build a starter .deepcoder/instructions.md string from a ProjectProfile.
 * Deterministic — same profile always produces the same output.
 */
export function buildStarterMd(profile: ProjectProfile): string {
  const lines: string[] = [
    "# Project (auto-generated by /init — review and edit)",
    "",
    "## Language & runtime",
    `Language: ${profile.lang}`,
    "",
    "## Key commands",
  ];

  const scriptEntries = Object.entries(profile.scripts);
  if (scriptEntries.length === 0) {
    lines.push("No commands detected.");
  } else {
    lines.push("| npm run ... | what it does |");
    lines.push("|---|---|");
    // Show the most important scripts first: dev, build, test, typecheck, then the rest
    const preferred = ["dev", "build", "test", "typecheck", "lint", "format", "start"];
    const ordered = [...scriptEntries].sort(([a], [b]) => {
      const ai = preferred.indexOf(a);
      const bi = preferred.indexOf(b);
      if (ai !== -1 && bi !== -1) return ai - bi;
      if (ai !== -1) return -1;
      if (bi !== -1) return 1;
      return a.localeCompare(b);
    });
    for (const [name, cmd] of ordered) {
      lines.push(`| \`npm run ${name}\` | \`${cmd}\` |`);
    }
  }

  lines.push("", "## Test");
  lines.push(`Framework: ${profile.testFramework ?? "none detected"}`);
  if (profile.testFramework) {
    if (profile.scripts.test) {
      lines.push(`\`npm test\`       # \`${profile.scripts.test}\``);
    }
    if (profile.scripts["test:unit"]) {
      lines.push(`\`npm run test:unit\`  # \`${profile.scripts["test:unit"]}\``);
    }
  }

  lines.push("", "## Lint / format");
  const linter = profile.linter ?? "none detected";
  const formatter = profile.formatter ?? "none detected";
  lines.push(`${linter} / ${formatter}`);

  lines.push("", "## TypeScript");
  if (profile.hasTsconfig) {
    lines.push(profile.tsStrict ? "strict: yes" : "strict: no");
  } else {
    lines.push("strict: null (no tsconfig.json detected)");
  }

  lines.push("", "## Source layout");
  if (profile.srcDirs.length === 0) {
    lines.push("(no source directories detected)");
  } else {
    for (const d of profile.srcDirs) {
      lines.push(`- ${d}/`);
    }
  }

  lines.push("", "## Architecture notes (add your own below)");
  lines.push("<!-- TODO: describe entry points, boundaries, conventions -->");

  return lines.join("\n") + "\n";
}
