/**
 * Phase 10E.8 — Pure logic for `/web` slash commands.
 *
 * PURE module: no terminal I/O, no real network, no live model, no side effects.
 * Every network dependency is injected via a fakeable seam (fetchImpl / searchProvider).
 * Every function returns deterministic data that the caller (the slash-command wiring)
 * renders into the TUI or plain-text output.
 *
 * Exported functions:
 *   webStatus   — `/web status`
 *   webSearch   — `/web search <query>`
 *   webFetch    — `/web fetch <url>`
 *   webTrace    — `/web trace`
 *   webClear    — `/web clear`
 */

import { redactSecrets } from "../workspace/redact.js";
import { fetchUrl, type FetchOptions, type FetchResult } from "./fetcher.js";
import {
  runWebSearch,
  type WebSearchProvider,
  type WebSearchOutcome,
  type WebSearchOptions,
} from "./searchProvider.js";
import { appendWebTrace, summarizeWebTrace, type WebTraceRecord } from "./trace.js";
import type { WebDomainPolicy } from "./types.js";
import type { WebConfig } from "../config/webConfig.js";
import { messageResult, type SlashResult } from "../cli/slashResult.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * All dependencies a `/web` command handler needs, except the trace (which is
 * passed and returned separately so the caller owns the session state).
 */
export interface WebCommandContext {
  config: WebConfig;
  searchProvider: WebSearchProvider;
  fetchImpl?: typeof fetch;
}

/**
 * Per-invocation metadata that must be generated by the caller (the wiring) so
 * this module stays pure — no Date.now(), no crypto.randomUUID(), no side effects.
 */
export interface WebCommandMeta {
  recordId: string;
  fetchedAt: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Maximum body chars to display in fetch output. */
const MAX_BODY_CHARS = 1200;

// ---------------------------------------------------------------------------
// /web status
// ---------------------------------------------------------------------------

/**
 * Produce a `SlashResult` describing the current web configuration.
 *
 * When web is disabled the output includes a one-line hint about how to enable
 * it (env var or config file). When enabled all relevant config fields are shown.
 */
export function webStatus(config: WebConfig): SlashResult {
  if (!config.enabled) {
    return messageResult(
      "Web access (disabled)",
      [
        "web: disabled",
        "enable with DEEPCODER_WEB=1 or .deepcoder/config.json web.enabled=true",
      ].join("\n"),
      "info",
    );
  }

  const allowed =
    config.allowedDomains.length > 0
      ? config.allowedDomains.join(", ")
      : "(any non-blocked)";
  const blocked =
    config.blockedDomains.length > 0
      ? config.blockedDomains.join(", ")
      : "(none)";

  const rows: string[][] = [
    ["enabled", "yes"],
    ["search provider", config.searchProvider],
    ["fetch", config.fetchEnabled ? "enabled" : "disabled"],
    ["allowed domains", allowed],
    ["blocked domains", blocked],
    ["max results", String(config.maxResults)],
    ["max fetch bytes", String(config.maxFetchBytes)],
    ["max returned chars", String(config.maxReturnedChars)],
    ["quarantine", config.quarantine ? "on" : "off"],
  ];

  return {
    kind: "table",
    title: "Web access",
    headers: ["setting", "value"],
    rows,
  };
}

// ---------------------------------------------------------------------------
// /web search <query>
// ---------------------------------------------------------------------------

/**
 * Execute a web search through the injected `searchProvider`.
 *
 * Refusals:
 *  - web disabled
 *  - search provider is `"none"` (no provider configured)
 *
 * On success the result contains a bounded list of results (capped to
 * config.maxResults) with stable ids ("r1", "r2", …). A trace record is
 * appended to the returned trace.
 *
 * The caller must provide a unique `recordId` and ISO `fetchedAt` string
 * via `meta` — this module never calls Date or crypto itself.
 */
export async function webSearch(
  query: string,
  ctx: WebCommandContext,
  meta: WebCommandMeta,
  trace: WebTraceRecord[],
): Promise<{ result: SlashResult; trace: WebTraceRecord[] }> {
  // -- Refuse when web is disabled ---------------------------------------
  if (!ctx.config.enabled) {
    return {
      result: messageResult(
        "Web search",
        "web is disabled — enable with DEEPCODER_WEB=1",
        "error",
      ),
      trace,
    };
  }

  // -- Build search options from config ----------------------------------
  const searchOpts: WebSearchOptions = {
    maxResults: ctx.config.maxResults,
  };

  // -- Execute search ----------------------------------------------------
  const outcome: WebSearchOutcome = await runWebSearch(
    query,
    searchOpts,
    ctx.searchProvider,
  );

  // -- Build trace record ------------------------------------------------
  const traceRecord: WebTraceRecord = {
    id: meta.recordId,
    kind: "search",
    query,
    fetchedAt: meta.fetchedAt,
    resultCount: outcome.ok ? outcome.results.length : 0,
    blocked: !outcome.ok,
    reason: outcome.ok ? undefined : outcome.reason,
  };
  const updatedTrace = appendWebTrace(trace, traceRecord);

  // -- Build result ------------------------------------------------------
  if (!outcome.ok) {
    const reason = outcome.reason
      ? redactSecrets(outcome.reason)
      : "search failed";
    return {
      result: messageResult("Web search", reason, "error"),
      trace: updatedTrace,
    };
  }

  // Format results: one block per result with id, title, url, snippet
  const lines: string[] = [];
  for (const r of outcome.results) {
    lines.push(`${r.id}  ${r.title}`);
    lines.push(`    ${r.url}`);
    if (r.snippet) {
      // Bounded snippet to avoid overflowing the terminal
      const snippet = r.snippet.length > 200
        ? r.snippet.slice(0, 200) + "…"
        : r.snippet;
      lines.push(`    ${snippet}`);
    }
    lines.push(""); // blank line between results
  }

  return {
    result: {
      kind: "message",
      title: `Web search — ${outcome.results.length} result(s)`,
      body: lines.join("\n").trimEnd(),
    },
    trace: updatedTrace,
  };
}

// ---------------------------------------------------------------------------
// /web fetch <url>
// ---------------------------------------------------------------------------

/**
 * Fetch a URL through the safe web fetcher using the injected `fetchImpl`.
 *
 * Refusals:
 *  - web disabled
 *  - fetch disabled
 *
 * On success the result contains the page title (if HTML), source URL, byte
 * count, char count, truncation info, and a bounded body snippet. A trace
 * record is appended to the returned trace.
 *
 * The caller must provide a unique `recordId` and ISO `fetchedAt` string
 * via `meta`.
 */
export async function webFetch(
  rawUrl: string,
  ctx: WebCommandContext,
  meta: WebCommandMeta,
  trace: WebTraceRecord[],
): Promise<{ result: SlashResult; trace: WebTraceRecord[] }> {
  // -- Refuse when web disabled ------------------------------------------
  if (!ctx.config.enabled) {
    return {
      result: messageResult(
        "Web fetch",
        "web is disabled — enable with DEEPCODER_WEB=1",
        "error",
      ),
      trace,
    };
  }

  // -- Refuse when fetch disabled ----------------------------------------
  if (!ctx.config.fetchEnabled) {
    return {
      result: messageResult(
        "Web fetch",
        "fetch is disabled in web config",
        "error",
      ),
      trace,
    };
  }

  // -- Build policy + options from config --------------------------------
  const policy: WebDomainPolicy = {
    allowedDomains: ctx.config.allowedDomains,
    blockedDomains: ctx.config.blockedDomains,
  };

  const fetchOpts: FetchOptions = {
    maxBytes: ctx.config.maxFetchBytes,
    maxChars: ctx.config.maxReturnedChars,
    timeoutMs: ctx.config.timeoutMs,
    redirects: ctx.config.redirects,
  };

  const fetchDeps = {
    policy,
    fetchImpl: ctx.fetchImpl,
  };

  // -- Execute fetch -----------------------------------------------------
  const result: FetchResult = await fetchUrl(rawUrl, fetchOpts, fetchDeps);

  // -- Build trace record ------------------------------------------------
  const traceRecord: WebTraceRecord = {
    id: meta.recordId,
    kind: "fetch",
    url: rawUrl,
    finalUrl: result.finalUrl,
    title: result.title,
    fetchedAt: meta.fetchedAt,
    bytesRead: result.bytesRead,
    charsReturned: result.charsReturned,
    blocked: result.blocked,
    reason: result.ok ? undefined : result.reason,
  };
  const updatedTrace = appendWebTrace(trace, traceRecord);

  // -- Build result ------------------------------------------------------
  if (!result.ok) {
    if (result.blocked) {
      const reason = result.reason
        ? redactSecrets(result.reason)
        : "denied by policy";
      return {
        result: messageResult(
          "Web fetch — blocked",
          `URL: ${redactSecrets(rawUrl)}\nReason: ${reason}`,
          "warn",
        ),
        trace: updatedTrace,
      };
    }

    const reason = result.reason
      ? redactSecrets(result.reason)
      : "fetch failed";
    return {
      result: messageResult("Web fetch — error", reason, "error"),
      trace: updatedTrace,
    };
  }

  // -- Success: display metadata + bounded body --------------------------
  const bodyLines: string[] = [];

  // Metadata header
  if (result.title) {
    bodyLines.push(`Title: ${redactSecrets(result.title)}`);
  }
  bodyLines.push(`Source: ${redactSecrets(result.finalUrl ?? rawUrl)}`);
  if (result.bytesRead !== undefined) {
    bodyLines.push(`Bytes: ${result.bytesRead}`);
  }
  if (result.charsReturned !== undefined) {
    bodyLines.push(`Chars: ${result.charsReturned}`);
  }
  if (result.truncated) {
    bodyLines.push("Note: content truncated");
  }
  if (ctx.config.quarantine) {
    bodyLines.push("⚠ Content is quarantined (untrusted)");
  }

  // Bounded body
  if (result.text) {
    let body = result.text;
    if (body.length > MAX_BODY_CHARS) {
      body = body.slice(0, MAX_BODY_CHARS) + "… (truncated)";
    }
    bodyLines.push("");
    bodyLines.push("--- body ---");
    bodyLines.push(body);
  }

  return {
    result: {
      kind: "message",
      title: "Web fetch",
      body: bodyLines.join("\n"),
    },
    trace: updatedTrace,
  };
}

// ---------------------------------------------------------------------------
// /web trace
// ---------------------------------------------------------------------------

/**
 * Produce a compact, multi-line trace summary from the given trace records.
 *
 * Delegates to `summarizeWebTrace` which already redacts secrets and formats
 * one line per record. Empty traces produce a short "(no web activity
 * recorded)" message.
 */
export function webTrace(trace: WebTraceRecord[]): SlashResult {
  const summary = summarizeWebTrace(trace);
  return messageResult("Web trace", summary);
}

// ---------------------------------------------------------------------------
// /web clear
// ---------------------------------------------------------------------------

/**
 * Return an empty trace array and a confirmation message.
 *
 * This is a pure function — it does not touch disk, the filesystem, or
 * persisted session state. The caller is responsible for replacing the
 * session's webTrace field with the returned empty array.
 */
export function webClear(): { trace: WebTraceRecord[]; result: SlashResult } {
  return {
    trace: [],
    result: messageResult("Web clear", "Web trace cleared."),
  };
}
